import Foundation

enum EmojiData {
    static let categories: [(String, [String])] = [
        ("Smileys", ["😀", "😃", "😄", "😁", "😆", "😅", "🤣", "😂", "🙂", "😊", "😇", "🥰", "😍", "🤩", "😘", "😎", "🤓", "🧐", "🤔", "🫡", "😏", "🥱", "😴", "🤯", "🥳", "😤", "😡", "🥺", "😢", "😭"]),
        ("Gestures", ["👋", "🤚", "✋", "🖖", "👌", "🤌", "🤏", "✌️", "🤞", "🫰", "🤙", "👍", "👎", "✊", "👊", "🤛", "🤜", "👏", "🙌", "🫶", "👐", "🤲", "🙏", "💪"]),
        ("Animals", ["🐶", "🐱", "🐭", "🐹", "🐰", "🦊", "🐻", "🐼", "🐨", "🐯", "🦁", "🐮", "🐷", "🐸", "🐵", "🐔", "🐧", "🐦", "🦅", "🦉", "🦇", "🐺", "🐗", "🐴", "🦄", "🐝", "🐛", "🦋", "🐌", "🐞"]),
        ("Food", ["🍎", "🍐", "🍊", "🍋", "🍌", "🍉", "🍇", "🍓", "🫐", "🍒", "🍑", "🥭", "🍍", "🥝", "🍅", "🥑", "🌽", "🥕", "🧅", "🍔", "🍕", "🌮", "🍜", "🍣", "🍩", "🍪", "🎂", "🍰", "☕️", "🧋"]),
        ("Activities", ["⚽️", "🏀", "🏈", "⚾️", "🥎", "🎾", "🏐", "🎮", "🕹️", "🎲", "🧩", "🎯", "🎳", "🎸", "🎹", "🥁", "🎨", "🧶", "🎭", "🎪"]),
        ("Travel", ["🚗", "🚕", "🚌", "🚎", "🏎️", "🚓", "🚑", "✈️", "🚀", "🛸", "🚢", "⛵️", "🏠", "🏢", "🏰", "🗼", "🗽", "⛩️", "🌋", "🏔️"]),
        ("Objects", ["⌚️", "📱", "💻", "⌨️", "🖥️", "🖨️", "💾", "💿", "📷", "🎥", "📺", "📻", "🔔", "📦", "📁", "📂", "📅", "📌", "📎", "✂️", "🔑", "🔒", "🔧", "🔨", "💡", "📖", "✏️", "🖊️", "🎒", "👓"]),
        ("Symbols", ["❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "💯", "⭐️", "🌟", "✨", "💫", "🔥", "💥", "❄️", "🌈", "☀️", "🌙", "⚡️", "💎", "🏆", "🎵", "🎶", "♻️", "✅", "❌", "⚠️", "🚫", "💤"]),
        ("Flags", ["🏁", "🚩", "🎌", "🏴", "🏳️", "🏳️‍🌈", "🇺🇸", "🇬🇧", "🇨🇳", "🇯🇵", "🇰🇷", "🇫🇷", "🇩🇪", "🇮🇹", "🇪🇸", "🇧🇷", "🇮🇳", "🇦🇺", "🇨🇦", "🇲🇽"]),
    ]

    static let keywords: [String: [String]] = {
        var map = [String: [String]]()
        for (category, emojis) in categories {
            let catLower = category.lowercased()
            for emoji in emojis {
                map[emoji, default: []].append(catLower)
            }
        }
        let specific: [String: [String]] = [
            // Smileys
            "😀": ["smile", "happy", "grin", "face"],
            "😃": ["smile", "happy", "grin", "face", "open"],
            "😄": ["smile", "happy", "grin", "face", "eyes"],
            "😁": ["smile", "happy", "grin", "teeth"],
            "😆": ["laugh", "happy", "squint", "xd"],
            "😅": ["sweat", "nervous", "laugh", "relief"],
            "🤣": ["rofl", "laugh", "rolling", "floor", "funny"],
            "😂": ["laugh", "cry", "joy", "tears", "funny", "lol"],
            "🙂": ["smile", "slight", "face"],
            "😊": ["smile", "blush", "happy", "shy"],
            "😇": ["angel", "halo", "innocent", "blessed"],
            "🥰": ["love", "hearts", "adore", "affection"],
            "😍": ["love", "heart", "eyes", "crush"],
            "🤩": ["star", "eyes", "excited", "wow", "amazing"],
            "😘": ["kiss", "love", "wink", "blow"],
            "😎": ["cool", "sunglasses", "awesome"],
            "🤓": ["nerd", "glasses", "smart", "geek"],
            "🧐": ["monocle", "curious", "inspect", "investigate"],
            "🤔": ["think", "thinking", "hmm", "wonder", "question"],
            "🫡": ["salute", "respect", "yes sir"],
            "😏": ["smirk", "sly", "suggestive"],
            "🥱": ["yawn", "tired", "bored", "sleepy"],
            "😴": ["sleep", "zzz", "tired", "snore"],
            "🤯": ["mind blown", "explode", "shocked", "wow"],
            "🥳": ["party", "celebrate", "birthday", "hooray"],
            "😤": ["angry", "mad", "huff", "frustrated"],
            "😡": ["angry", "mad", "rage", "furious", "red"],
            "🥺": ["pleading", "puppy eyes", "please", "sad", "cute"],
            "😢": ["cry", "sad", "tear", "upset"],
            "😭": ["cry", "sob", "sad", "wail", "bawl"],

            // Gestures
            "👋": ["wave", "hello", "hi", "bye", "hand"],
            "🤚": ["hand", "stop", "raised", "back"],
            "✋": ["hand", "stop", "high five", "palm"],
            "🖖": ["vulcan", "spock", "star trek", "hand"],
            "👌": ["ok", "okay", "perfect", "fine", "hand"],
            "🤌": ["pinch", "italian", "chef", "kiss", "hand"],
            "🤏": ["pinch", "small", "tiny", "little", "hand"],
            "✌️": ["peace", "victory", "two", "hand"],
            "🤞": ["cross", "fingers", "luck", "hope", "hand"],
            "🫰": ["money", "snap", "hand"],
            "🤙": ["call", "hang loose", "shaka", "hand"],
            "👍": ["thumbs up", "like", "yes", "good", "approve"],
            "👎": ["thumbs down", "dislike", "no", "bad"],
            "✊": ["fist", "power", "punch", "solidarity"],
            "👊": ["fist bump", "punch", "bro"],
            "🤛": ["fist", "left", "bump"],
            "🤜": ["fist", "right", "bump"],
            "👏": ["clap", "applause", "bravo", "congrats"],
            "🙌": ["raise", "hands", "hooray", "celebrate", "praise"],
            "🫶": ["heart", "hands", "love", "care"],
            "👐": ["open", "hands", "jazz"],
            "🤲": ["palms", "hands", "pray", "receive"],
            "🙏": ["pray", "please", "thank", "hands", "namaste", "hope"],
            "💪": ["muscle", "strong", "flex", "power", "arm", "bicep"],

            // Animals
            "🐶": ["dog", "puppy", "pet", "woof"],
            "🐱": ["cat", "kitty", "pet", "meow"],
            "🐭": ["mouse", "rat", "rodent"],
            "🐹": ["hamster", "pet", "rodent"],
            "🐰": ["rabbit", "bunny", "pet", "easter"],
            "🦊": ["fox", "clever", "orange"],
            "🐻": ["bear", "teddy", "grizzly"],
            "🐼": ["panda", "bear", "bamboo"],
            "🐨": ["koala", "australia"],
            "🐯": ["tiger", "cat", "stripe"],
            "🦁": ["lion", "king", "cat", "mane"],
            "🐮": ["cow", "moo", "farm"],
            "🐷": ["pig", "oink", "farm"],
            "🐸": ["frog", "toad", "ribbit"],
            "🐵": ["monkey", "ape", "primate"],
            "🐔": ["chicken", "hen", "rooster", "farm"],
            "🐧": ["penguin", "bird", "arctic", "cold"],
            "🐦": ["bird", "tweet", "fly"],
            "🦅": ["eagle", "bird", "fly", "freedom"],
            "🦉": ["owl", "bird", "night", "wise"],
            "🦇": ["bat", "vampire", "night", "fly"],
            "🐺": ["wolf", "howl"],
            "🐗": ["boar", "pig", "wild"],
            "🐴": ["horse", "pony", "ride"],
            "🦄": ["unicorn", "horse", "magic", "rainbow"],
            "🐝": ["bee", "honey", "buzz", "insect"],
            "🐛": ["bug", "caterpillar", "insect", "worm"],
            "🦋": ["butterfly", "insect", "pretty", "fly"],
            "🐌": ["snail", "slow", "shell"],
            "🐞": ["ladybug", "insect", "bug", "beetle"],

            // Food
            "🍎": ["apple", "red", "fruit", "healthy"],
            "🍐": ["pear", "fruit", "green"],
            "🍊": ["orange", "tangerine", "citrus", "fruit"],
            "🍋": ["lemon", "citrus", "yellow", "sour", "fruit"],
            "🍌": ["banana", "fruit", "yellow"],
            "🍉": ["watermelon", "melon", "fruit", "summer"],
            "🍇": ["grape", "wine", "fruit", "purple"],
            "🍓": ["strawberry", "berry", "fruit", "red"],
            "🫐": ["blueberry", "berry", "fruit", "blue"],
            "🍒": ["cherry", "fruit", "red"],
            "🍑": ["peach", "fruit"],
            "🥭": ["mango", "fruit", "tropical"],
            "🍍": ["pineapple", "fruit", "tropical"],
            "🥝": ["kiwi", "fruit", "green"],
            "🍅": ["tomato", "vegetable", "red"],
            "🥑": ["avocado", "guacamole", "green", "healthy"],
            "🌽": ["corn", "vegetable", "maize"],
            "🥕": ["carrot", "vegetable", "orange"],
            "🧅": ["onion", "vegetable"],
            "🍔": ["burger", "hamburger", "fast food", "meat"],
            "🍕": ["pizza", "slice", "italian", "food"],
            "🌮": ["taco", "mexican", "food"],
            "🍜": ["noodle", "ramen", "soup", "bowl", "asian"],
            "🍣": ["sushi", "fish", "japanese", "food"],
            "🍩": ["donut", "doughnut", "sweet", "dessert"],
            "🍪": ["cookie", "sweet", "biscuit", "dessert"],
            "🎂": ["cake", "birthday", "celebrate", "party", "dessert"],
            "🍰": ["cake", "slice", "shortcake", "dessert", "sweet"],
            "☕️": ["coffee", "tea", "hot", "drink", "cup", "cafe"],
            "🧋": ["boba", "bubble tea", "milk tea", "drink"],

            // Activities
            "⚽️": ["soccer", "football", "ball", "sport"],
            "🏀": ["basketball", "ball", "sport", "nba"],
            "🏈": ["football", "american", "ball", "sport", "nfl"],
            "⚾️": ["baseball", "ball", "sport"],
            "🥎": ["softball", "ball", "sport"],
            "🎾": ["tennis", "ball", "sport", "racket"],
            "🏐": ["volleyball", "ball", "sport"],
            "🎮": ["game", "controller", "video game", "play", "console", "gaming"],
            "🕹️": ["joystick", "game", "arcade", "retro"],
            "🎲": ["dice", "game", "chance", "roll", "board game"],
            "🧩": ["puzzle", "piece", "jigsaw", "game"],
            "🎯": ["target", "dart", "bullseye", "goal"],
            "🎳": ["bowling", "pin", "ball", "sport"],
            "🎸": ["guitar", "music", "rock", "instrument"],
            "🎹": ["piano", "keyboard", "music", "instrument"],
            "🥁": ["drum", "music", "beat", "instrument"],
            "🎨": ["art", "paint", "palette", "color", "draw", "creative"],
            "🧶": ["yarn", "knit", "craft", "wool"],
            "🎭": ["theater", "theatre", "drama", "mask", "perform"],
            "🎪": ["circus", "tent", "carnival"],

            // Travel
            "🚗": ["car", "automobile", "drive", "vehicle", "red"],
            "🚕": ["taxi", "cab", "car", "ride", "yellow"],
            "🚌": ["bus", "transit", "vehicle", "school"],
            "🚎": ["trolley", "bus", "transit", "tram"],
            "🏎️": ["race", "car", "fast", "speed", "formula"],
            "🚓": ["police", "car", "cop", "emergency"],
            "🚑": ["ambulance", "emergency", "hospital", "medical"],
            "✈️": ["plane", "airplane", "flight", "travel", "fly", "airport"],
            "🚀": ["rocket", "space", "launch", "fast", "startup"],
            "🛸": ["ufo", "alien", "space", "flying saucer"],
            "🚢": ["ship", "boat", "cruise", "sea"],
            "⛵️": ["sailboat", "boat", "sail", "sea", "wind"],
            "🏠": ["home", "house", "building"],
            "🏢": ["office", "building", "work", "business"],
            "🏰": ["castle", "palace", "medieval", "kingdom"],
            "🗼": ["tower", "tokyo", "japan"],
            "🗽": ["statue", "liberty", "new york", "usa", "freedom"],
            "⛩️": ["shrine", "torii", "japan", "temple"],
            "🌋": ["volcano", "mountain", "lava", "eruption"],
            "🏔️": ["mountain", "snow", "peak", "nature"],

            // Objects
            "⌚️": ["watch", "time", "clock", "wrist"],
            "📱": ["phone", "mobile", "iphone", "cell", "smartphone"],
            "💻": ["laptop", "computer", "mac", "macbook", "code", "dev"],
            "⌨️": ["keyboard", "type", "computer", "input"],
            "🖥️": ["desktop", "computer", "monitor", "screen", "display"],
            "🖨️": ["printer", "print", "paper"],
            "💾": ["floppy", "disk", "save", "storage", "retro"],
            "💿": ["cd", "disc", "dvd", "music", "album"],
            "📷": ["camera", "photo", "picture", "snap", "photography"],
            "🎥": ["movie", "camera", "film", "video", "cinema"],
            "📺": ["tv", "television", "screen", "watch", "show"],
            "📻": ["radio", "music", "broadcast"],
            "🔔": ["bell", "notification", "alert", "ring"],
            "📦": ["box", "package", "delivery", "shipping"],
            "📁": ["folder", "file", "directory", "organize"],
            "📂": ["folder", "file", "open", "directory"],
            "📅": ["calendar", "date", "schedule", "event", "plan"],
            "📌": ["pin", "location", "mark", "push pin"],
            "📎": ["paperclip", "clip", "attach", "attachment"],
            "✂️": ["scissors", "cut", "trim"],
            "🔑": ["key", "password", "lock", "access", "security"],
            "🔒": ["lock", "security", "password", "private", "secure"],
            "🔧": ["wrench", "tool", "fix", "repair", "settings"],
            "🔨": ["hammer", "tool", "build", "construct"],
            "💡": ["idea", "light", "bulb", "bright", "lamp", "think"],
            "📖": ["book", "read", "open", "study", "education"],
            "✏️": ["pencil", "write", "edit", "draw"],
            "🖊️": ["pen", "write", "sign", "ink"],
            "🎒": ["backpack", "bag", "school", "travel"],
            "👓": ["glasses", "eyeglasses", "read", "spectacles", "vision"],

            // Symbols
            "❤️": ["heart", "love", "red", "valentine"],
            "🧡": ["heart", "love", "orange"],
            "💛": ["heart", "love", "yellow"],
            "💚": ["heart", "love", "green"],
            "💙": ["heart", "love", "blue"],
            "💜": ["heart", "love", "purple"],
            "🖤": ["heart", "love", "black", "dark"],
            "🤍": ["heart", "love", "white"],
            "💯": ["hundred", "perfect", "score", "100"],
            "⭐️": ["star", "favorite", "rating", "gold"],
            "🌟": ["star", "glow", "sparkle", "shine"],
            "✨": ["sparkle", "magic", "shine", "glitter", "new"],
            "💫": ["dizzy", "star", "shooting", "magic"],
            "🔥": ["fire", "hot", "lit", "flame", "trending"],
            "💥": ["boom", "explosion", "crash", "bang", "pow"],
            "❄️": ["snow", "cold", "ice", "winter", "freeze"],
            "🌈": ["rainbow", "color", "pride", "weather"],
            "☀️": ["sun", "sunny", "weather", "bright", "day", "summer"],
            "🌙": ["moon", "night", "crescent", "sleep", "dark"],
            "⚡️": ["lightning", "bolt", "electric", "power", "fast", "energy", "thunder"],
            "💎": ["diamond", "gem", "jewel", "precious", "crystal"],
            "🏆": ["trophy", "winner", "champion", "award", "gold", "first"],
            "🎵": ["music", "note", "song", "melody", "audio", "sound"],
            "🎶": ["music", "notes", "song", "melody", "audio", "sound"],
            "♻️": ["recycle", "green", "environment", "eco"],
            "✅": ["check", "done", "yes", "complete", "correct", "approve"],
            "❌": ["cross", "no", "wrong", "delete", "remove", "cancel"],
            "⚠️": ["warning", "alert", "caution", "danger"],
            "🚫": ["no", "prohibited", "forbidden", "stop", "ban"],
            "💤": ["sleep", "zzz", "tired", "nap", "rest"],

            // Flags
            "🏁": ["flag", "checkered", "race", "finish"],
            "🚩": ["flag", "red", "warning"],
            "🎌": ["flag", "crossed", "japan"],
            "🏴": ["flag", "black", "pirate"],
            "🏳️": ["flag", "white", "surrender"],
            "🏳️‍🌈": ["flag", "rainbow", "pride", "lgbtq", "gay"],
            "🇺🇸": ["flag", "usa", "america", "united states", "us"],
            "🇬🇧": ["flag", "uk", "britain", "england", "united kingdom"],
            "🇨🇳": ["flag", "china", "chinese"],
            "🇯🇵": ["flag", "japan", "japanese"],
            "🇰🇷": ["flag", "korea", "korean", "south korea"],
            "🇫🇷": ["flag", "france", "french"],
            "🇩🇪": ["flag", "germany", "german"],
            "🇮🇹": ["flag", "italy", "italian"],
            "🇪🇸": ["flag", "spain", "spanish"],
            "🇧🇷": ["flag", "brazil", "brazilian"],
            "🇮🇳": ["flag", "india", "indian"],
            "🇦🇺": ["flag", "australia", "australian"],
            "🇨🇦": ["flag", "canada", "canadian"],
            "🇲🇽": ["flag", "mexico", "mexican"],
        ]
        for (emoji, words) in specific {
            map[emoji, default: []].append(contentsOf: words)
        }
        return map
    }()
}
